[project]
name = "time-pay-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "asyncpg>=0.30.0",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.43",
]
